version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: barefoot
    ports:
      - '3308:3306'
    networks:
      - backend
    volumes:
      - mysql_data:/var/lib/mysql

networks:
  backend:
    driver: bridge

volumes:
  mysql_data:

